import { runArrayScripts } from "./scripts/runArrayScripts";
import { runBinarySearchTreeScripts } from "./scripts/runBinarySearchTreeScripts";
import { runBinaryTreeScripts } from "./scripts/runBinaryTreeScripts";
import { runDynamicProgrammingScripts } from "./scripts/runDynamicProgrammingScripts";
import { runFamousAlgorithmScripts } from "./scripts/runFamousAlgorithmScripts";
import { runGraphScripts } from "./scripts/runGraphScripts";
import { runGreedyAlgorithmScripts } from "./scripts/runGreedyAlgorithmScripts";
import { runHeapScripts } from "./scripts/runHeapScripts";
import { runLinkedListScripts } from "./scripts/runLinkedListScripts";
import { runRecursionScripts } from "./scripts/runRecursionScripts";
import { runSearchingScripts } from "./scripts/runSearchingScripts";
import { runSortingScripts } from "./scripts/runSortingScripts";
import { runStackScripts } from "./scripts/runStackScripts";
import { runStringScripts } from "./scripts/runStringScripts";
import { runTrieScripts } from "./scripts/runTrieScripts";

(async () => {
  runArrayScripts();
  runBinarySearchTreeScripts();
  runBinaryTreeScripts();
  runDynamicProgrammingScripts();
  runFamousAlgorithmScripts();
  runGreedyAlgorithmScripts();
  runGraphScripts();
  runHeapScripts();
  runLinkedListScripts();
  runRecursionScripts();
  runSearchingScripts();
  runSortingScripts();
  runStackScripts();
  runStringScripts();
  runTrieScripts();
})();